services:
  db:
    container_name: haus-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: haus
    volumes:
      - haus-db:/var/lib/postgresql/data

volumes:
  haus-db:
    external: false
